[package]
name = "remote-do-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
tokio = { version = "1.43.0", features = ["io-std", "io-util", "process"] }
tokio-fd = "=0.3.0"
tokio-util = "=0.7.13"
wtransport = { version = "=0.5.0", features = ["quinn"] }
